# -*- coding: utf-8 -*-
"""rpg_estudo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V44CrTs5G6Q7s_7Ec3jJof_ai2ueQTS6
"""

#molde de personagens
class Personagem:
  def __init__(self,nome,vida,ataque):
    self.nome = nome
    self.vida = vida
    self.ataque = ataque
    self.nivel = 1

  def atacar(self,inimigo):
    print(f"{self.nome} ataca {inimigo.nome} causando {self.ataque} de dano!")
    inimigo.vida -= self.ataque

  def esta_vivo(self):
        return self.vida > 0

  def subir_nivel(self):
        self.nivel += 1
        aumento_vida = 10
        aumento_ataque = 2
        self.vida += aumento_vida
        self.ataque += aumento_ataque
        print(f"{self.nome} subiu para o nível {self.nivel}!")
        print(f"Vida aumentou para {self.vida}, ataque agora é {self.ataque}.")

#personagens
ragall = Personagem("Ragall, O Bárbaro",60,30)
vendrix = Personagem("Vendrix, O Velho Sábio",10,80)
arana = Personagem("Arana, A Flecha da Mata",30,50)

goblin_minion = Personagem("Goblin Batedor",5,5)
goblin_ranged = Personagem("Goblin Arqueiro",2,8)
goblin_brute = Personagem("Goblin Brutamontes",20,2)
goblin_boss = Personagem("Gruorrgh, Goblin Chefe",50,15)

#############################################################
#funções de combate

def combate_ragall_goblin_minion():
  while ragall.esta_vivo() and goblin_minion.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{ragall.nome}: {ragall.vida} de vida")
      print(f"{goblin_minion.nome}: {goblin_minion.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          ragall.atacar(goblin_minion)
          if goblin_minion.esta_vivo():
              goblin_minion.atacar(ragall)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
  if not ragall.esta_vivo():
      print("Você foi derrotado...")
  elif not goblin_minion.esta_vivo():
      print("Você venceu!")

def combate_ragall_goblin_ranged():
    while ragall.esta_vivo() and goblin_ranged.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{ragall.nome}: {ragall.vida} de vida")
      print(f"{goblin_ranged.nome}: {goblin_ranged.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          ragall.atacar(goblin_ranged)
          if goblin_ranged.esta_vivo():
              goblin_ranged.atacar(ragall)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not ragall.esta_vivo():
      print("Você foi derrotado...")
    elif not goblin_ranged.esta_vivo():
      print("Você venceu!")

def combate_ragall_goblin_brute():
    while ragall.esta_vivo() and goblin_brute.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{ragall.nome}: {ragall.vida} de vida")
      print(f"{goblin_brute.nome}: {goblin_brute.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          ragall.atacar(goblin_brute)
          if goblin_brute.esta_vivo():
              goblin_brute.atacar(ragall)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not ragall.esta_vivo():
       print("Você foi derrotado...")
    elif not goblin_brute.esta_vivo():
       print("Você venceu!")

def combate_ragall_goblin_boss():
    while ragall.esta_vivo() and goblin_boss.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{ragall.nome}: {ragall.vida} de vida")
      print(f"{goblin_boss.nome}: {goblin_boss.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          ragall.atacar(goblin_boss)
          if goblin_boss.esta_vivo():
              goblin_boss.atacar(ragall)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not ragall.esta_vivo():
      print("Você foi derrotado...")
    elif not goblin_boss.esta_vivo():
      print("Você venceu!")
#############################################################
def combate_vendrix_goblin_minion():
    while vendrix.esta_vivo() and goblin_minion.esta_vivo():
        print("\n--- NOVO TURNO ---")
        print(f"{vendrix.nome}: {vendrix.vida} de vida")
        print(f"{goblin_minion.nome}: {goblin_minion.vida} de vida")

        acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
        if acao == "a":
            vendrix.atacar(goblin_minion)
            if goblin_minion.esta_vivo():
                goblin_minion.atacar(vendrix)
        elif acao == "f":
            print("Você fugiu da batalha!")
            break
        else:
            print("Comando inválido.")
    if not vendrix.esta_vivo():
        print("Você foi derrotado...")
    elif not goblin_minion.esta_vivo():
        print("Você venceu!")

def combate_vendrix_goblin_ranged():
    while vendrix.esta_vivo() and goblin_ranged.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{vendrix.nome}: {vendrix.vida} de vida")
      print(f"{goblin_ranged.nome}: {goblin_ranged.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          vendrix.atacar(goblin_ranged)
          if goblin_ranged.esta_vivo():
              goblin_ranged.atacar(vendrix)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not vendrix.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_ranged.esta_vivo():
          print("Você venceu!")

def combate_vendrix_goblin_brute():
    while vendrix.esta_vivo() and goblin_brute.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{vendrix.nome}: {vendrix.vida} de vida")
      print(f"{goblin_brute.nome}: {goblin_brute.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          vendrix.atacar(goblin_brute)
          if goblin_brute.esta_vivo():
              goblin_brute.atacar(vendrix)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not vendrix.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_brute.esta_vivo():
          print("Você venceu!")

def combate_vendrix_goblin_boss():
    while vendrix.esta_vivo() and goblin_boss.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{vendrix.nome}: {vendrix.vida} de vida")
      print(f"{goblin_boss.nome}: {goblin_boss.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          vendrix.atacar(goblin_boss)
          if goblin_boss.esta_vivo():
              goblin_boss.atacar(vendrix)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not vendrix.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_boss.esta_vivo():
          print("Você venceu!")
#############################################################
def combate_arana_goblin_minion():
    while arana.esta_vivo() and goblin_minion.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{arana.nome}: {arana.vida} de vida")
      print(f"{goblin_minion.nome}: {goblin_minion.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          arana.atacar(goblin_minion)
          if goblin_minion.esta_vivo():
              goblin_minion.atacar(arana)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not arana.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_minion.esta_vivo():
          print("Você venceu!")

def combate_arana_goblin_ranged():
    while arana.esta_vivo() and goblin_ranged.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{arana.nome}: {arana.vida} de vida")
      print(f"{goblin_ranged.nome}: {goblin_ranged.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          arana.atacar(goblin_ranged)
          if goblin_ranged.esta_vivo():
              goblin_ranged.atacar(arana)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not arana.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_ranged.esta_vivo():
          print("Você venceu!")

def combate_arana_goblin_brute():
    while arana.esta_vivo() and goblin_brute.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{arana.nome}: {arana.vida} de vida")
      print(f"{goblin_brute.nome}: {goblin_brute.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          arana.atacar(goblin_brute)
          if goblin_brute.esta_vivo():
              goblin_brute.atacar(arana)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not arana.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_brute.esta_vivo():
          print("Você venceu!")

def combate_arana_goblin_boss():
    while arana.esta_vivo() and goblin_boss.esta_vivo():
      print("\n--- NOVO TURNO ---")
      print(f"{arana.nome}: {arana.vida} de vida")
      print(f"{goblin_boss.nome}: {goblin_boss.vida} de vida")

      acao = input("Escolha (a) atacar ou (f) fugir: ").lower()
      if acao == "a":
          arana.atacar(goblin_boss)
          if goblin_boss.esta_vivo():
              goblin_boss.atacar(arana)
      elif acao == "f":
          print("Você fugiu da batalha!")
          break
      else:
          print("Comando inválido.")
    if not arana.esta_vivo():
          print("Você foi derrotado...")
    elif not goblin_boss.esta_vivo():
          print("Você venceu!")
#############################################################
#funções de combate quando for necessário na história
"""
combate_ragall_goblin_minion()
combate_ragall_goblin_ranged()
combate_ragall_goblin_brute()
combate_ragall_goblin_boss()
combate_vendrix_goblin_minion()
combate_vendrix_goblin_ranged()
combate_vendrix_goblin_brute()
combate_vendrix_goblin_boss()
combate_arana_goblin_minion()
combate_arana_goblin_ranged()
combate_arana_goblin_brute()
combate_arana_goblin_boss()
"""
#############################################################
#história

print("Escolha sua personagem:\n[1]Ragall, O Bárbaro\n[2]Vendrix, o Velho Sábio\n[3]Arana, a Flecha da Mata\n\n")
char = int(input())
if char <= 0 or char > 3:
  print("GAME OVER")
if char == 1:
  print("Ragall é atacado por goblins na floresta")
  combate_ragall_goblin_minion()
  ragall.subir_nivel()
if char == 2:
  print("Vendrix é atacado por goblins na floresta")
  combate_vendrix_goblin_minion()
  vendrix.subir_nivel()
if char == 3:
  print("Arana é atacada por goblins na floresta")
  combate_arana_goblin_minion()
  arana.subir_nivel()